name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: cd src && shards install
    - name: Run Build!
      run: |
           mkdir ./out/
           mkdir ./out/linux-x64 
           mkdir ./out/linux-arm64-unknown 
           cd src
           crystal build -o ../out/linux-x64/crystalic --release main.cr
    - uses: actions/upload-artifact@v3
      with: 
        name: linux-x64 
        path: ./out/linux-x64/*
